### ISSUE TITLE
Big Bone Lick State Park on Beaver Rd.

### ISSUE THREAD

**Issue by vicchi** [vicchi/vaguely-rude-places#26]
_From @goldicecream on July 11, 2014 16:50_

...Just thought that maybe it should be added.

Big Bone Lick State Park
3380 Beaver Rd
Union, KY 41091

Also, maybe Dry Ridge, KY.  And Ballplay, TN.

...I've driven from Michigan to Florida way too many times...

_Copied from original issue: vicchi/maps.geotastic.org#26_

**Comment by vicchi** [comment]
Big Bone Lick State Park is already on the map; see http://maps.geotastic.org/vaguely-rude-places/index.html?id=17&lang=en.

I've opened up Issue #31 to add Ball Play, TN.

Is Dry Ridge rude? Or am I missing something.

**Comment by goldicecream** [comment]
I suppose it's too vaguely rude to be included... I think it only seems
pervy if you really reach for it.
