### ISSUE TITLE
Misplaced Fannie Bay

### ISSUE THREAD

**Issue by paul-butcher** [vicchi/vaguely-rude-places#35]
There is an incorrect entry for Fannie Bay, Northern Territory, Australia:
http://maps.geotastic.org/rude/?id=202&lang=en

It is in the same location as Petting, Germany:
http://maps.geotastic.org/rude/?id=203&lang=en

This is the real Fannie Bay
http://maps.geotastic.org/rude/?id=201&lang=en

**Comment by vicchi** [comment]
Definitely a data error, which I'll resolve on the next site update.

**Comment by vicchi** [comment]
Fixed and deployed - https://www.vaguelyrudeplacesmap.com/?id=202&lang=en
