### ISSUE TITLE
Add Rectum .... you know what it means ;)

### ISSUE THREAD

**Issue by drainbamage84** [vicchi/vaguely-rude-places#38]
https://tools.wmflabs.org/geohack/geohack.php?language=en&params=52_019_039_N_6_034_019_E_type:city_scale:25000_region:NL&pagename=Rectum_(village)

Very little village in the Netherlands.

**Comment by vicchi** [comment]
Added as https://www.vaguelyrudeplacesmap.com/?id=283&lang=en
