### ISSUE TITLE
Tuggen-Wangen in Switzerland

### ISSUE THREAD

**Issue by samkass** [vicchi/vaguely-rude-places#46]
There are many here in Switzerland. Not far from Zürich there is Wangen, right next to Tuggen. Yes, there is a "Tuggen Wangen" exit sign. I've never seen anyone getting off there.

There are also several places named Butzbach. (Literally, "stream of slugs".) (In Germany there's a Bützsee, or slug lake.)

Fuchs is a common last name here, and there are places named after various Fuchs. A lot of people like to explore nearby Fuchsloch (loch is "hole").

It's not a place name, but my all time favorite sign I saw in Zürich was a religious group with a tent labeled with the German translation for "Jesus seeks you". In big, bold letters it proclaims: "Jesus sucht dich".

**Comment by vicchi** [comment]
@samkass Nicely spotted. I assume you mean this _Wangen_ (https://www.openstreetmap.org/node/240071055#map=14/47.1914/8.8948) ... ?

There seems to be the beginnings of a German specific version here, as there is already an Italian one, but for now I think one isn't enough so I'll keep this on the back burner for Butzbach,.

**Comment by samkass** [comment]
That’s the one. I live nearby there now, and even took a photo of that exit sign. I’ll try to pay more attention to specific Swiss/German locations so I have more Fuchs to give.

**Comment by vicchi** [comment]
Added Wangen as https://www.vaguelyrudeplacesmap.com/?id=278&lang=en - though not pushed live yet. Will close this issue when that's done - and thanks!
