### ISSUE TITLE
There are three Mount Buggerys in Australia.

### ISSUE THREAD

**Issue by nickzoic** [vicchi/vaguely-rude-places#69]
No, really, there are: https://en.wikipedia.org/wiki/Mount_Buggery

**Comment by nickzoic** [comment]
Very proud to have reported Issue #69 in the Vaguely Rude Places repo.

**Comment by vicchi** [comment]
@nickzoic The Alpine Shire Mount Buggery is already at place id 198; the remaining 2 will be place ids 316 and 317 when I deploy an update this weekend. Thanks!

**Comment by nickzoic** [comment]
Truly a proud moment :-)
